apiVersion: v1
kind: Service
metadata:
  name: my-node-service
  namespace: "namespace_value"
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - port: 3000
      targetPort: 3000
      
  