apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: "namespace_value"
spec:
   type: ClusterIP
   ports: 
      - targetPort: 3306
        port: 3306
   selector:
         app: node-app