apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: "namespace_value"
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        # the name of image on dockerhub
        # image: samargooda/node_project
        # the name of image on nexus with ip of cluster and the port of service
        image: 10.105.233.131:8123/node_project:latest
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: node-conf    
              key: mysql_root_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: node-conf    
              key: mysql_database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: node-conf    
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: node-conf    
              key: mysql_password
       
              